export interface Sat {
        Name: string ,
		Country_Org_of_UN_Registry: string,
		Country_of_Operator_Owner: string,
		Operator_Owner: string,
		Users: string,
		Purpose: string,
		Detailed_Purpose:string ,
		Class_of_Orbit: string,
		Type_of_Orbit: string,
		Longitude_of_GEO_indegrees: number,
		Perigee_km: string,
		Apogee_km: string,
		Eccentricity: number,
		Inclination_indegrees: number,
		Period_inminutes:string,
		Launch_Mass_inkg: string,
		Dry_Mass_kg: string,
		Power_watts: string,
		Date_of_Launch: string,
		Expected_Lifetime: string,
		Contractor: string,
		Country_of_Contractor: string,
		Launch_Site: string,
		Launch_Vehicle: string,
		COSPAR_Number: string,
		NORAD_Number: number,
		Comments:string,
		Comment2: string,
		Source_Used_for_Orbital_Data: string,
		Source1: string,
		Source2: string,
		Source3: string,
		Source4: string,
		Source5: string,
		Source6: string
}
